# Generated by Django 4.1.3 on 2022-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='writer',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='start',
        ),
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='mapimg',
            field=models.ImageField(blank=True, null=True, upload_to='map/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
